using JWPlayer.ApiGateway.Schemas;
using System.Text.Json.Serialization;

namespace JWPlayer.MediaApiService.Model;
public class MediaObjectSchema : ObjectSchema<MediaMetadata>//, IEquatable<MediaObjectSchema>
{
    /// <summary>
    /// Media upload status
    /// </summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>
    /// Audio or video
    /// </summary>
    [JsonPropertyName("media_type")]
    public string? MediaType { get; set; }

    /// <summary>
    /// Indicates whether or not the media is hosted with JW Player or not
    /// </summary>
    [JsonPropertyName("hosting_type")]
    public string? HostingType { get; set; }

    /// <summary>
    /// One of <see cref="MediaUploadMimeType"/>"/>
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string? MimeType { get; set; }

    /// <summary>
    /// Message describing an issue uploading or processing the media
    /// </summary>
    [JsonPropertyName("error_message")]
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// ID for the media, generated by a non-JW Player platform or program
    /// </summary>
    [JsonPropertyName("external_id")]
    public string? ExternalId { get; set; }

    /// <summary>
    /// Length of the media in seconds
    /// </summary>
    [JsonPropertyName("duration")]
    public double? Duration { get; set; }

    /// <summary>
    /// Starting point to trim the video
    /// </summary>
    [JsonPropertyName("trim_in_point")]
    public DateTime? TrimInPoint { get; set; }

    /// <summary>
    /// Ending point to trim the video
    /// </summary>
    [JsonPropertyName("trim_out_point")]
    public DateTime? TrimOutPoint { get; set; }

    public MediaObjectSchema() : base(
        "media")
    {
        Metadata = new MediaMetadata();
    }
}
